#!/usr/bin/env bash

# Gum driven CuriOS install script as NixOS package.
# Meant to be run during an NixOS ISO installation.
# !IMPORTANT! Run this script as sudo
# It will create 3 partitions for '/boot', '/' and a 8Go swap
# If disk encryption is choosed, the encrypted LUKS partition will contain LVM
# partitions for '/' and a 8Go swap.
#
# Dependencies: gum, parted, git, mkpasswd.
# Test it with:
# nix-shell shell.nix

#------------- Colors -------------#
readonly RED="\033[31;1m"      # Red and bold
readonly GREEN="\033[32;1m"    # Green and bold
readonly BLUE="\033[34;1m"     # Blue and bold
readonly GREY="\033[37;1m"     # Grey and bold
readonly YELLOW="\033[33;1;3m" # Yellow, bold and italic
#readonly YELLOWBLK="\033[33;1;5m"  # Yellow, bold and slow blink
#readonly UNDL="\033[4m"            # Underlined
#readonly BOLD="\033[1m"            # Bold
readonly NC="\033[0m" # No Color

#------------- Variables init
readonly SCRIPT_VERSION="0.10"
CURIOS_INSTALL_PATH="."
CURIOS_SRC_PATH="."
SCRIPT_PATH="$(dirname "$0")"
LANG_CHOICE=0
PC_HOSTNAME="CuriOS"
SELECTED_DISK=""
SELECTED_LOCALE="en_US.UTF-8"
SELECTED_LOCALE_CONSOLE="us"
SELECTED_TZ=""
USERNAME="nixos"
FULLNAME=""
HASHED_USER_PASSWD=""
ENCRYPT_DISK=0
DISK_LUKS_KEY=""
GPU_VENDOR_DETECTED=""
GPU_INSTALL=0
CONFIRM_INSTALL=0
RPI4_INSTALL=0
NIXOS_CONFIG_DIR="/mnt/etc/nixos"
DO_DOTFILES_INSTALL=1
VERBOSE=0
# Pre configured timezone based on user language - adjust to choose_lang() list order.
LOCALES_TZ=(
  "Europe/Amsterdam"
  "Europe/Athens"
  "Europe/Belgrade"
  "Europe/Berlin"
  "Europe/Brussels"
  "Europe/Bucharest"
  "Europe/Budapest"
  "Europe/Copenhagen"
  "Europe/Dublin"
  "Europe/Helsinki"
  "Europe/Istanbul"
  "Europe/Kyiv"
  "Europe/Lisbon"
  "Europe/Ljubljana"
  "Europe/London"
  "Europe/Luxembourg"
  "Europe/Madrid"
  "Europe/Monaco"
  "Europe/Moscow"
  "Europe/Oslo"
  "Europe/Paris"
  "Europe/Prague"
  "Europe/Riga"
  "Europe/Rome"
  "Europe/Stockholm"
  "Europe/Tallinn"
  "Europe/Vienna"
  "Europe/Vilnius"
  "Europe/Warsaw"
  "Europe/Zurich"
  "US/Alaska"
  "US/Aleutian"
  "US/Arizona"
  "US/Central"
  "US/East-Indiana"
  "US/Eastern"
  "US/Hawaii"
  "US/Indiana-Starke"
  "US/Michigan"
  "US/Mountain"
  "US/Pacific"
  "US/Samoa"
  "America/Argentina/Buenos_Aires"
  "America/Bogota"
  "America/Caracas"
  "America/Chicago"
  "America/Denver"
  "America/Los_Angeles"
  "America/Mexico_City"
  "America/New_York"
  "America/Phoenix"
  "America/Sao_Paulo"
  "America/Toronto"
  "America/Vancouver"
  "Asia/Bangkok"
  "Asia/Dubai"
  "Asia/Hong_Kong"
  "Asia/Jerusalem"
  "Asia/Kolkata"
  "Asia/Riyadh"
  "Asia/Seoul"
  "Asia/Shanghai"
  "Asia/Singapore"
  "Asia/Taipei"
  "Asia/Tokyo"
  "Australia/Adelaide"
  "Australia/Brisbane"
  "Australia/Darwin"
  "Australia/Melbourne"
  "Australia/Perth"
  "Australia/Sydney"
  "Pacific/Auckland"
  "Pacific/Fiji"
  "Etc/GMT"
)

# Mapping from language choice index to a default timezone from the LOCALES_TZ list
# Indices: 0:C, 1:us, 2:gb, 3:fr, 4:es, 5:de, 6:zh, 7:hi, 8:ja, 9:pt, 10:ru, 11:it, 12:ko, 13:ar, 14:nl, 15:pl, 16:sv, 17:tr, 18:cs, 19:da, 20:hu, 21:no, 22:he, 23:uk, 24:el
# Note: The user provided a list of 25 languages in choose_lang()
declare -A LANG_TO_TZ_DEFAULT=(
  [0]="Etc/GMT"
  [1]="US/Eastern"
  [2]="Europe/London"
  [3]="Europe/Paris"
  [4]="Europe/Madrid"
  [5]="Europe/Berlin"
  [6]="Asia/Shanghai"
  [7]="Asia/Kolkata"
  [8]="Asia/Tokyo"
  [9]="Europe/Lisbon"
  [10]="Europe/Moscow"
  [11]="Europe/Rome"
  [12]="Asia/Seoul"
  [13]="Asia/Riyadh"
  [14]="Europe/Amsterdam"
  [15]="Europe/Warsaw"
  [16]="Europe/Stockholm"
  [17]="Europe/Istanbul"
  [18]="Europe/Prague"
  [19]="Europe/Copenhagen"
  [20]="Europe/Budapest"
  [21]="Europe/Oslo"
  [22]="Asia/Jerusalem"
  [23]="Europe/Kyiv"
  [24]="Europe/Athens"
)

#------------- Print help function
usage() {
  echo -e "CuriOS installer version ${SCRIPT_VERSION}
* Gum interface for CuriOS install script *

${GREY}USAGE:${NC}
  curios-install [options]

${GREY}OPTIONS:${NC}
  ${GREY}-h, --help${NC}         Print this message.
  ${GREY}--rpi4${NC}             Raspberry PI 4 installation.
  ${GREY}-v, --verbose${NC}      Print more information.
  ${GREY}--version${NC}          Print version number and exit."
  exit 0
}

#------------- Scripts arguments parse options
ARGS=$(getopt --longoptions="verbose,version,rpi4,help" --options ":hv" --name "$0" -- "$@")
eval set -- "$ARGS"

while true; do
  case "$1" in
  -v | --verbose)
    VERBOSE=1
    shift
    ;;
  -h | --help)
    usage
    ;;
  --version)
    echo "$SCRIPT_VERSION"
    exit 0
    ;;
  --rpi4)
    VERBOSE=1
    RPI4_INSTALL=1
    shift
    ;;
  --)
    shift
    break
    ;;
  *)
    break
    ;;
  esac
done

if [ $VERBOSE -eq 1 ]; then
  echo -e "Script current path: ${SCRIPT_PATH}"
fi

#------------- Check curios-sources files
if [ $RPI4_INSTALL -eq 1 ]; then
  CURIOS_INSTALL_PATH="."
  CURIOS_SRC_PATH="."
  NIXOS_CONFIG_DIR="/etc/nixos/"
else
  CURIOS_INSTALL_PATH=$(dirname "$(realpath "$(which curios-install)")")
  CURIOS_SRC_PATH=$(realpath "$CURIOS_INSTALL_PATH"/../share/curios)
fi
if [ $VERBOSE -eq 1 ]; then
  echo -e "Package store path: ${CURIOS_SRC_PATH}"
fi
if [ ! -f "$CURIOS_SRC_PATH"/configuration.nix ]; then
  echo -e "${RED}configuration.nix file not found!${NC}"
  exit 1
fi
if [ ! -f "$CURIOS_SRC_PATH"/settings.nix ]; then
  echo -e "${RED}settings.nix file not found!${NC}"
  exit 1
fi
if [ ! -d "$CURIOS_SRC_PATH"/modules/ ]; then
  echo -e "${RED}modules directory not found!${NC}"
  exit 1
fi
if [ ! -d "$CURIOS_SRC_PATH"/pkgs/ ]; then
  echo -e "${RED}pkgs directory not found!${NC}"
  exit 1
fi

#------------- Check dependencies
available() { command -v "$1" >/dev/null; }

if ! available git; then
  echo -e "${RED}git command not found!${NC}"
  exit 2
fi
if ! available mkpasswd; then
  echo -e "${RED}mkpasswd command not found!${NC}"
  exit 2
fi
if ! available gum; then
  echo -e "${RED}gum command not found!${NC}"
  exit 2
fi
if ! available jq; then
  echo -e "${RED}jq command not found!${NC}"
  exit 2
fi
if [ $RPI4_INSTALL -eq 0 ]; then
  if ! available parted; then
    echo -e "${RED}parted command not found!${NC}"
    exit 2
  fi
  if ! available cryptsetup; then
    echo -e "${RED}cryptsetup command not found!${NC}"
    exit 2
  fi
  if ! available mkfs; then
    echo -e "${RED}mkfs command not found!${NC}"
    exit 2
  fi
else
  if ! available rpi-eeprom-update; then
    echo -e "${RED}rpi-eeprom-update command not found!${NC}"
    exit 2
  fi
fi

#------------- Check internet connectivity
if nc -zw1 github.com 443; then
  echo -e "Internet connectivity: ${GREEN}Check${NC}"
else
  echo -e "${RED}No internet connectivity - an internet connection is required!${NC}"
  exit 1
fi

#------------- Settings and checks
# This script must be run as root
if [ "$EUID" -ne 0 ]; then
  echo -e "${RED}This script MUST be run as root:${NC} sudo curios-install" >&2
  exit 1
fi

setterm -blink on

# A standard gum message box, for printing error message
display_error() {
  gum format "# !! Error" "$1"
  read -r -p "Press Enter to continue..."
}

#------------- Choose language
# See: https://en.wikipedia.org/wiki/List_of_ISO_639_language_codes
choose_lang() {
  echo "Choose your language:"
  selection=$(gum choose \
    "C: No localization" \
    "us: US English" \
    "gb: British English" \
    "fr: Français" \
    "es: Español" \
    "de: Deutsch" \
    "zh: 中文 (汉语) - Chinese (simplified)" \
    "hi: हिन्दी - Hindi" \
    "ja: 日本語 - Japanese" \
    "pt: Português" \
    "ru: Русский язык - Russian" \
    "it: Italiano" \
    "ko: 한국어 - Korean" \
    "ar: اَلْعَرَبِيَّةُ Arabic" \
    "nl: Nederlands" \
    "pl: Polski" \
    "sv: Svenska" \
    "tr: Türkçe" \
    "cs: Čeština" \
    "da: Dansk" \
    "hu: Magyar nyelv" \
    "no: Norsk" \
    "he: עברית Hebrew" \
    "uk: Українська - Ukrainian" \
    "el: Ελληνικά - Greek")

  exit_status=$?
  if [ $exit_status -ne 0 ]; then
    echo "Program terminated." >&2
    exit 1
  fi

  # Extract the code (part before the colon)
  selection_code=$(echo "$selection" | cut -d':' -f1)

  case $selection_code in
  C)
    SELECTED_LOCALE="C.UTF-8"
    SELECTED_LOCALE_CONSOLE="us"
    LANG_CHOICE=0
    ;;
  us)
    SELECTED_LOCALE="en_US.UTF-8"
    SELECTED_LOCALE_CONSOLE="us"
    LANG_CHOICE=1
    ;;
  gb)
    SELECTED_LOCALE="en_GB.UTF-8"
    SELECTED_LOCALE_CONSOLE="gb"
    LANG_CHOICE=2
    ;;
  fr)
    SELECTED_LOCALE="fr_FR.UTF-8"
    SELECTED_LOCALE_CONSOLE="fr"
    LANG_CHOICE=3
    ;;
  es)
    SELECTED_LOCALE="es_ES.UTF-8"
    SELECTED_LOCALE_CONSOLE="es"
    LANG_CHOICE=4
    ;;
  de)
    SELECTED_LOCALE="de_DE.UTF-8"
    SELECTED_LOCALE_CONSOLE="de"
    LANG_CHOICE=5
    ;;
  zh)
    SELECTED_LOCALE="zh_CN.UTF-8"
    SELECTED_LOCALE_CONSOLE="zh"
    LANG_CHOICE=6
    ;;
  hi)
    SELECTED_LOCALE="hi_IN.UTF-8"
    SELECTED_LOCALE_CONSOLE="hi"
    LANG_CHOICE=7
    ;;
  ja)
    SELECTED_LOCALE="ja_JP.UTF-8"
    SELECTED_LOCALE_CONSOLE="ja"
    LANG_CHOICE=8
    ;;
  pt)
    SELECTED_LOCALE="pt_PT.UTF-8"
    SELECTED_LOCALE_CONSOLE="pt"
    LANG_CHOICE=9
    ;;
  ru)
    SELECTED_LOCALE="ru_RU.UTF-8"
    SELECTED_LOCALE_CONSOLE="ru"
    LANG_CHOICE=10
    ;;
  it)
    SELECTED_LOCALE="it_IT.UTF-8"
    SELECTED_LOCALE_CONSOLE="it"
    LANG_CHOICE=11
    ;;
  ko)
    SELECTED_LOCALE="ko_KR.UTF-8"
    SELECTED_LOCALE_CONSOLE="ko"
    LANG_CHOICE=12
    ;;
  ar)
    SELECTED_LOCALE="ar_SA.UTF-8"
    SELECTED_LOCALE_CONSOLE="ar"
    LANG_CHOICE=13
    ;;
  nl)
    SELECTED_LOCALE="nl_NL.UTF-8"
    SELECTED_LOCALE_CONSOLE="nl"
    LANG_CHOICE=14
    ;;
  pl)
    SELECTED_LOCALE="pl_PL.UTF-8"
    SELECTED_LOCALE_CONSOLE="pl"
    LANG_CHOICE=15
    ;;
  sv)
    SELECTED_LOCALE="sv_SE.UTF-8"
    SELECTED_LOCALE_CONSOLE="sv"
    LANG_CHOICE=16
    ;;
  tr)
    SELECTED_LOCALE="tr_TR.UTF-8"
    SELECTED_LOCALE_CONSOLE="tr"
    LANG_CHOICE=17
    ;;
  cs)
    SELECTED_LOCALE="cs_CZ.UTF-8"
    SELECTED_LOCALE_CONSOLE="cs"
    LANG_CHOICE=18
    ;;
  da)
    SELECTED_LOCALE="da_DK.UTF-8"
    SELECTED_LOCALE_CONSOLE="da"
    LANG_CHOICE=19
    ;;
  hu)
    SELECTED_LOCALE="hu_HU.UTF-8"
    SELECTED_LOCALE_CONSOLE="hu"
    LANG_CHOICE=20
    ;;
  no)
    SELECTED_LOCALE="no_NO.UTF-8"
    SELECTED_LOCALE_CONSOLE="no"
    LANG_CHOICE=21
    ;;
  he)
    SELECTED_LOCALE="he_IL.UTF-8"
    SELECTED_LOCALE_CONSOLE="he"
    LANG_CHOICE=22
    ;;
  uk)
    SELECTED_LOCALE="uk_UA.UTF-8"
    SELECTED_LOCALE_CONSOLE="uk"
    LANG_CHOICE=23
    ;;
  el)
    SELECTED_LOCALE="el_GR.UTF-8"
    SELECTED_LOCALE_CONSOLE="el"
    LANG_CHOICE=24
    ;;
  esac

  loadkeys $SELECTED_LOCALE_CONSOLE
  set_tz
}

#------------- Choose timezone
# See: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
set_tz() {
  echo "Choose your timezone:"
  local DEFAULT_TZ="${LANG_TO_TZ_DEFAULT[$LANG_CHOICE]}"
  SELECTED_TZ=$(gum choose --selected="$DEFAULT_TZ" "${LOCALES_TZ[@]}")
  exit_status=$?

  if [ $exit_status -ne 0 ]; then
    choose_lang
    return
  fi

  if [ -z "$SELECTED_TZ" ]; then
    choose_lang
    return
  fi

  set_hostname
}

#------------- Choose machine name
set_hostname() {
  echo "Enter this machine hostname:"
  result=$(gum input --placeholder "Hostname" --value "$PC_HOSTNAME")
  exit_status=$?

  if [ $exit_status -ne 0 ]; then
    set_tz
    return
  fi

  PC_HOSTNAME=$result
  if ! [[ $PC_HOSTNAME =~ ^[[:alnum:].]+$ ]]; then
    display_error "Invalid hostname! It could only contain alphanumerical or '.' characters."
    set_hostname
  else
    set_username
  fi
}

#------------- Choose username
set_username() {
  echo "Enter your username (id):"
  result=$(gum input --placeholder "Username" --value "$USERNAME")
  exit_status=$?

  if [ $exit_status -ne 0 ]; then
    set_hostname
    return
  fi

  USERNAME=$result
  if [ -z "$USERNAME" ]; then
    display_error "username cannot be empty."
    set_username
  elif ! [[ $USERNAME =~ ^[[:alnum:]]+$ ]]; then
    display_error "Invalid username! It could only contain alphanumerical characters."
    set_username
  else
    set_fullname
  fi
}

#------------- Choose user full name
set_fullname() {
  echo "Enter your full name:"
  result=$(gum input --placeholder "Full Name" --value "$FULLNAME")
  exit_status=$?

  if [ $exit_status -ne 0 ]; then
    set_username
    return
  fi

  FULLNAME=$result
  if [ -z "$FULLNAME" ]; then
    FULLNAME="Dwight K. Schrute"
  fi
  if ! [[ $FULLNAME =~ ^[[:alnum:][:space:].]+$ ]]; then
    display_error "Invalid full name! it could only contain alphanumerical, '.' or space characters."
    set_fullname
  else
    set_user_passwd
  fi
}

#------------- Set user password
set_user_passwd() {
  echo "Enter your password (6 characters minimum):"
  password=$(gum input --password --placeholder "Password")
  if [ $? -ne 0 ]; then
    set_fullname
    return
  fi

  echo "Confirm your password:"
  confirm=$(gum input --password --placeholder "Confirm Password")
  if [ $? -ne 0 ]; then
    set_user_passwd
    return
  fi

  # Compare and check password length
  if [ "${#password}" -le 5 ]; then
    display_error "Password is too short! It should be at least 6 characters long."
    set_user_passwd
  elif [[ "$password" != "$confirm" ]]; then
    display_error "Password mismatch! Password and confirmation are different."
    set_user_passwd
  else
    HASHED_USER_PASSWD=$(mkpasswd -m yescrypt "$password")
    if [ $RPI4_INSTALL -eq 1 ]; then
      confirm_install
    else
      choose_disk
    fi
  fi
}

#------------- Choose install disk
choose_disk() {
  DEVICES_LIST=()
  for device in $(lsblk -A -pdn -o NAME); do
    DISK_SIZE=$(lsblk -dn -o SIZE "$device")
    DISK_MODEL=$(lsblk -dn -o MODEL "$device")
    DEVICES_LIST+=("$device ($DISK_SIZE - $DISK_MODEL)")
  done

  echo "Choose which disk to install CuriOS on:"
  selection=$(gum choose "${DEVICES_LIST[@]}")
  exit_status=$?

  if [ $exit_status -ne 0 ]; then
    set_user_passwd
    return
  fi

  SELECTED_DISK=$(echo "$selection" | cut -d' ' -f1)
  choose_disk_encryption
}

choose_disk_encryption() {
  if gum confirm "Should your disk be fully encrypted (highly recommended)?"; then
    echo "Enter your passphrase for the full disk encryption (8 characters minimum):"
    passphrase=$(gum input --password --placeholder "Passphrase")
    if [ $? -ne 0 ]; then
      choose_disk
      return
    fi

    echo "Confirm your passphrase:"
    confirm=$(gum input --password --placeholder "Confirm Passphrase")
    if [ $? -ne 0 ]; then
      choose_disk_encryption
      return
    fi

    if [ ${#passphrase} -le 7 ]; then
      display_error "Passphrase is too short! It should be at least 8 characters long."
      choose_disk_encryption
    elif ! [[ $passphrase =~ ^[[:alnum:]]+$ ]]; then
      display_error "Invalid passphrase! it could only contain alphanumerical characters."
      choose_disk_encryption
    elif [[ "$passphrase" != "$confirm" ]]; then
      display_error "Passphrase mismatch! Passphrase and confirmation are different."
      choose_disk_encryption
    else
      ENCRYPT_DISK=1
      DISK_LUKS_KEY=$passphrase
      hardware_detection_gpu
    fi
  else
    ENCRYPT_DISK=0
    hardware_detection_gpu
  fi
}

hardware_detection_gpu() {
  NB_GPU=$(lspci | grep -ci "vga")
  if [ $VERBOSE -eq 1 ]; then
    echo -e "${GREY}${NB_GPU}${NC} GPU found."
  fi
  if [ "$NB_GPU" -ge 1 ]; then
    GPU=$(lspci -nn | grep -i "vga")
    if echo "$GPU" | grep -qi "amd"; then
      GPU_VENDOR_DETECTED="AMD"
    elif echo "$GPU" | grep -qi "intel"; then
      GPU_VENDOR_DETECTED="Intel"
    elif echo "$GPU" | grep -qi "nvidia"; then
      GPU_VENDOR_DETECTED="Nvidia"
    fi
    if [[ -n $GPU_VENDOR_DETECTED ]]; then
      if gum confirm "GPU detected: $GPU_VENDOR_DETECTED. Would you like to install the hardware pilot (recommended)? It may imply the installation of unfree packages."; then
        GPU_INSTALL=1
      else
        GPU_INSTALL=0
      fi
    fi
  fi
  confirm_install
}

confirm_install() {
  if gum confirm "Proceed with installation? Your hard drive disk will be formatted and all data erased."; then
    CONFIRM_INSTALL=1
  else
    echo "Program terminated without any installation." >&2
  fi
}

clear
if [ -f "$CURIOS_SRC_PATH"/logo.txt ]; then
  tte -i "$CURIOS_SRC_PATH"/logo.txt --anchor-text c --canvas-width 0 sweep --final-gradient-stops 12488B 2AA1B3 --final-gradient-steps 12 12 --final-gradient-direction diagonal
fi
choose_lang

if [ $VERBOSE -eq 1 ]; then
  echo -e "${YELLOW}Current options:${NC}"
  echo "bin path: $CURIOS_INSTALL_PATH"
  echo "locale: $SELECTED_LOCALE"
  echo "keyboard: $SELECTED_LOCALE_CONSOLE"
  echo "time zone: $SELECTED_TZ"
  echo "hostname: $PC_HOSTNAME"
  echo "username: $USERNAME"
  echo "user hashed password: $HASHED_USER_PASSWD"
  echo "user full name: $FULLNAME"
  echo "install on disk: $SELECTED_DISK"
  echo "encrypt disk: $ENCRYPT_DISK"
  echo "disk LUKS key: $DISK_LUKS_KEY"
  echo "GPU hardware vendor: $GPU_VENDOR_DETECTED"
  echo "install GPU driver: $GPU_INSTALL"
  echo "RPI4 install: $RPI4_INSTALL"
  echo "NixOS config dir: $NIXOS_CONFIG_DIR"
  echo -e "${YELLOW}End of options.${NC}"
fi

#------------- Format disk function
format_disk() {
  set -eu
  echo -e "${GREEN}================================${NC}"
  echo -e "${GREEN}================================${NC}"
  echo -e "${BLUE}Formatting disk:${NC} ${SELECTED_DISK}"
  if [ $ENCRYPT_DISK -eq 1 ]; then
    echo -e "${YELLOW}Disk will be fully encrypted...${NC}"
  fi

  # Check if disk exist
  if fdisk -l "$SELECTED_DISK"; then
    SELECTED_DISK1="$SELECTED_DISK"1
    SELECTED_DISK2="$SELECTED_DISK"2
    if [[ $SELECTED_DISK =~ ^"/dev/nvme" ]]; then
      SELECTED_DISK1="$SELECTED_DISK"p1
      SELECTED_DISK2="$SELECTED_DISK"p2
    fi
  else
    echo -e "${RED}Disk ${SELECTED_DISK} not found!${NC}"
    exit 2
  fi
  swapoff -av
  #umount "$SELECTED_DISK"*
  wipefs -af "$SELECTED_DISK"

  echo -e "${GREEN}================================${NC}"
  echo -e "${GREEN}================================${NC}"
  echo -e "${BLUE}UEFI partitioning...${NC}"
  parted --script "$SELECTED_DISK" mklabel gpt
  parted --script "$SELECTED_DISK" mkpart ESP fat32 1MB 1024MB
  parted --script "$SELECTED_DISK" set 1 esp on
  parted --script "$SELECTED_DISK" mkpart system 1024MB 100%

  echo -e "${GREEN}================================${NC}"
  echo -e "${GREEN}================================${NC}"
  echo -e "${BLUE}Filesystem formatting...${NC}"
  mkfs.fat -F 32 -n boot "$SELECTED_DISK1"

  LVM_MAPPED_DEVICE=$SELECTED_DISK2
  if [ $ENCRYPT_DISK -eq 1 ]; then
    echo -e "${GREEN}================================${NC}"
    echo -e "${GREEN}================================${NC}"
    echo -e "${BLUE}Creating encrypted partition...${NC}"
    DEVICE_NAME="cryptroot" # /dev/mapper/ name
    LVM_MAPPED_DEVICE="/dev/mapper/$DEVICE_NAME"
    cryptsetup -q --label="curiosystem" --type=luks2 luksFormat "$SELECTED_DISK2" <<<"${DISK_LUKS_KEY}"
    # open the encrypted partition and map it to /dev/mapper/$DEVICE_NAME
    echo -n "$DISK_LUKS_KEY" | cryptsetup luksOpen "$SELECTED_DISK2" $DEVICE_NAME -
  fi

  echo -e "${GREEN}================================${NC}"
  echo -e "${GREEN}================================${NC}"
  echo -e "${BLUE}Creating LVM volumes...${NC}"
  pvcreate "$LVM_MAPPED_DEVICE"
  # create a volume group inside
  vgcreate curioslvm "$LVM_MAPPED_DEVICE"
  # create the swap volume
  lvcreate --size 8G curioslvm --name swap
  # create the root volume (100% of free disk)
  lvcreate -l 100%FREE curioslvm --name root
  if [ $VERBOSE -eq 1 ]; then
    #pvdisplay "$LVM_MAPPED_DEVICE"
    #vgdisplay "$LVM_MAPPED_DEVICE"
    lvdisplay
    if [ $ENCRYPT_DISK -eq 1 ]; then
      cryptsetup status "$LVM_MAPPED_DEVICE"
    fi
  fi

  # Filesystem formatting
  mkfs.ext4 -L nixos /dev/mapper/curioslvm-root
  mkswap -L swap /dev/mapper/curioslvm-swap

  # DEBUG
  # Unmount and remove volumes:
  #umount /dev/mapper/curioslvm-home && umount /dev/mapper/curioslvm-root
  #lvremove /dev/curioslvm/home && lvremove /dev/curioslvm/root && lvremove /dev/curioslvm/swap
  #vgchange -an curioslvm
  #vgremove curioslvm
  #pvremove "$LVM_MAPPED_DEVICE"
}

#------------- CuriOS dotfiles install, see: https://github.com/CuriosLabs/curios-dotfiles
dotfiles_install() {
  echo -e "${GREEN}================================${NC}"
  echo -e "${GREEN}================================${NC}"
  echo -e "${BLUE}Custom dotfiles installation...${NC}"
  local SKEL_DIR="/mnt/etc/skel/"
  local HOME_DIR="/mnt/home/*/"
  mkdir -p "$SKEL_DIR"
  curios-dotfiles --lang "$SELECTED_LOCALE_CONSOLE" "$SKEL_DIR"
  for DIR in $HOME_DIR; do
    if [[ -d "$DIR" && "$DIR" != */lost+found/ ]]; then
      curios-dotfiles --lang "$SELECTED_LOCALE_CONSOLE" "$DIR"
      # TODO: Any way to predict OWNER at this stage ?
      chown -R 1000:100 "$DIR"
    fi
  done
}

if [ $CONFIRM_INSTALL -eq 1 ]; then
  clear
  INSTALL_START_TIME=$SECONDS
  if [ $VERBOSE -eq 1 ]; then
    lsblk -A -pdn -o NAME
  fi
  if [ $RPI4_INSTALL -eq 0 ]; then
    format_disk
    echo -e "${GREEN}================================${NC}"
    echo -e "${GREEN}================================${NC}"
    echo -e "${BLUE}Mounting system...${NC}"
    sleep 2s
    if ! mountpoint -q /mnt; then
      mount /dev/disk/by-label/nixos /mnt
    fi
    mkdir -p /mnt/boot
    if ! mountpoint -q /mnt/boot; then
      mount -o umask=077 /dev/disk/by-partlabel/ESP /mnt/boot
    fi
    if [[ $(swapon -s | wc -l) -eq 1 ]]; then
      swapon /dev/disk/by-label/swap
    fi
    mkdir -p /mnt/home
  else
    echo -e "${GREEN}================================${NC}"
    echo -e "${GREEN}================================${NC}"
    echo -e "${BLUE}Mounting RPI system...${NC}"
    mount /dev/disk/by-label/FIRMWARE /mnt
    # Updating RPI firmware
    BOOTFS=/mnt rpi-eeprom-update -d -a
  fi

  if [ $VERBOSE -eq 1 ]; then
    lsblk -A -lo NAME,SIZE,TYPE,MOUNTPOINTS,PARTLABEL,UUID
  fi

  if [ $RPI4_INSTALL -eq 0 ]; then
    echo -e "${GREEN}================================${NC}"
    echo -e "${GREEN}================================${NC}"
    echo -e "${BLUE}Create basic configuration...${NC}"
    nixos-generate-config --root /mnt --no-filesystems
  fi

  echo -e "${GREEN}================================${NC}"
  echo -e "${GREEN}================================${NC}"
  echo -e "${BLUE}Preparing configurations files...${NC}"
  install -D -m 644 -t "$NIXOS_CONFIG_DIR"/ "$CURIOS_SRC_PATH"/*.nix
  install -D -m 644 -t "$NIXOS_CONFIG_DIR"/ "$CURIOS_SRC_PATH"/*.json
  install -D -m 644 -t "$NIXOS_CONFIG_DIR"/ "$CURIOS_SRC_PATH"/logo.txt
  install -D -m 644 -t "$NIXOS_CONFIG_DIR"/modules/ "$CURIOS_SRC_PATH"/modules/*.nix
  install -D -m 644 -t "$NIXOS_CONFIG_DIR"/modules/desktop-apps/ "$CURIOS_SRC_PATH"/modules/desktop-apps/*.nix
  install -D -m 644 -t "$NIXOS_CONFIG_DIR"/modules/desktop-apps/ "$CURIOS_SRC_PATH"/modules/desktop-apps/*.png
  install -D -m 644 -t "$NIXOS_CONFIG_DIR"/modules/desktop-apps/ "$CURIOS_SRC_PATH"/modules/desktop-apps/*.svg
  install -D -m 644 -t "$NIXOS_CONFIG_DIR"/modules/filesystems/ "$CURIOS_SRC_PATH"/modules/filesystems/*.nix
  install -D -m 644 -t "$NIXOS_CONFIG_DIR"/modules/hardened/ "$CURIOS_SRC_PATH"/modules/hardened/*.nix
  install -D -m 644 -t "$NIXOS_CONFIG_DIR"/modules/hardware/ "$CURIOS_SRC_PATH"/modules/hardware/*.nix
  install -D -m 644 -t "$NIXOS_CONFIG_DIR"/modules/platforms/ "$CURIOS_SRC_PATH"/modules/platforms/*.nix
  install -D -m 644 -t "$NIXOS_CONFIG_DIR"/pkgs/curios-dotfiles/ "$CURIOS_SRC_PATH"/pkgs/curios-dotfiles/default.nix
  install -D -m 644 -t "$NIXOS_CONFIG_DIR"/pkgs/curios-manager/ "$CURIOS_SRC_PATH"/pkgs/curios-manager/default.nix
  install -D -m 644 -t "$NIXOS_CONFIG_DIR"/pkgs/curios-manager-applet/ "$CURIOS_SRC_PATH"/pkgs/curios-manager-applet/default.nix
  install -D -m 644 -t "$NIXOS_CONFIG_DIR"/pkgs/snitch/ "$CURIOS_SRC_PATH"/pkgs/snitch/default.nix

  # User settings
  sed "s/users\..*/users.${USERNAME} = {/g" -i "$NIXOS_CONFIG_DIR"/settings.nix
  sed "s/description = \".*/description = \"${FULLNAME}\";/g" -i "$NIXOS_CONFIG_DIR"/settings.nix
  sed "s#initialHashedPassword = \".*#initialHashedPassword = \"${HASHED_USER_PASSWD}\";#g" -i "$NIXOS_CONFIG_DIR"/settings.nix

  # Update modules.json with selected locale, keyboard, time zone and hostname:
  jq --arg locale "$SELECTED_LOCALE" \
    --arg kbd "$SELECTED_LOCALE_CONSOLE" \
    --arg tz "$SELECTED_TZ" \
    --arg host "$PC_HOSTNAME" \
    '.curios.system.i18n.locale = $locale | .curios.system.keyboard = $kbd | .curios.system.timeZone = $tz | .curios.system.hostname = $host' \
    "$NIXOS_CONFIG_DIR"/modules.json >/tmp/modules.json && mv /tmp/modules.json "$NIXOS_CONFIG_DIR"/modules.json
  # platform settings:
  OPTION_PLATFORM_RPI4=false
  OPTION_PLATFORM_AMD64=true
  OPTION_BOOTEFI=true
  OPTION_FS_LUKS=true
  OPTION_FS_MINI=false
  if [ $RPI4_INSTALL -eq 0 ]; then
    OPTION_PLATFORM_RPI4=false
    OPTION_PLATFORM_AMD64=true
    OPTION_BOOTEFI=true
    # filesystems settings:
    if [ $ENCRYPT_DISK -eq 1 ]; then
      OPTION_FS_LUKS=true
      OPTION_FS_MINI=false
    else
      OPTION_FS_LUKS=false
      OPTION_FS_MINI=true
    fi
  else
    OPTION_PLATFORM_RPI4=true
    OPTION_PLATFORM_AMD64=false
    OPTION_BOOTEFI=false
    OPTION_FS_LUKS=false
    OPTION_FS_MINI=false
  fi
  jq --argjson rpi4 "$OPTION_PLATFORM_RPI4" \
    --argjson amd64 "$OPTION_PLATFORM_AMD64" \
    --argjson efi "$OPTION_BOOTEFI" \
    --argjson luks "$OPTION_FS_LUKS" \
    --argjson mini "$OPTION_FS_MINI" \
    '.curios.platform.amd64.enable = $amd64 | .curios.platform.rpi4.enable = $rpi4 | .curios.filesystems.luks.enable = $luks | .curios.filesystems.minimal.enable = $mini' \
    "$NIXOS_CONFIG_DIR"/modules.json >/tmp/modules.json && mv /tmp/modules.json "$NIXOS_CONFIG_DIR"/modules.json
  # GPU settings:
  OPTION_GPU_AMD=false
  OPTION_GPU_NVIDIA=false
  OPTION_GPU_INTEL=false
  OPTION_KERNEL_LATEST=true
  if [[ "$GPU_INSTALL" -eq 1 && "$GPU_VENDOR_DETECTED" == "AMD" ]]; then
    echo "Enabling AMD GPU..."
    OPTION_GPU_AMD=true
  elif [[ "$GPU_INSTALL" -eq 1 && "$GPU_VENDOR_DETECTED" == "Intel" ]]; then
    echo "Enabling Intel GPU..."
    OPTION_GPU_INTEL=true
  elif [[ "$GPU_INSTALL" -eq 1 && "$GPU_VENDOR_DETECTED" == "Nvidia" ]]; then
    echo "Enabling Nvidia GPU..."
    OPTION_GPU_NVIDIA=true
    # Switch to LTS kernel by default for Nvidia GPU
    OPTION_KERNEL_LATEST=false
  fi
  jq --argjson gpuAmd "$OPTION_GPU_AMD" \
    --argjson gpuIntel "$OPTION_GPU_INTEL" \
    --argjson gpuNvidia "$OPTION_GPU_NVIDIA" \
    --argjson kernelLatest "$OPTION_KERNEL_LATEST" \
    '.curios.hardware.amdGpu.enable = $gpuAmd | .curios.hardware.intelGpu.enable = $gpuIntel | .curios.hardware.nvidiaGpu.enable = $gpuNvidia | .curios.bootefi.kernel.latest = $kernelLatest' \
    "$NIXOS_CONFIG_DIR"/modules.json >/tmp/modules.json && mv /tmp/modules.json "$NIXOS_CONFIG_DIR"/modules.json

  echo -e "${GREEN}================================${NC}"
  echo -e "${GREEN}================================${NC}"
  echo -e "${BLUE}Launching NixOS installer...${NC}"
  # Configure Nix channel
  NIX_CHANNEL_URL=$(grep -oP -m 1 'channel\s*=\s*"\K[^"]+' "$NIXOS_CONFIG_DIR"/configuration.nix)
  if [ -z "$NIX_CHANNEL_URL" ]; then
    echo -e "${RED}Nix channel not found in configuration.nix!${NC}"
    exit 1
  fi
  echo "Adding channel: $NIX_CHANNEL_URL"
  nix-channel --add "$NIX_CHANNEL_URL" nixos
  nix-channel --update
  if [ $RPI4_INSTALL -eq 0 ]; then
    nixos-install --cores 0 --no-root-passwd
  else
    nixos-rebuild boot
  fi

  if [ $DO_DOTFILES_INSTALL -eq 1 ]; then
    dotfiles_install
  fi

  INSTALL_END_TIME=$SECONDS
  DURATION=$((INSTALL_END_TIME - INSTALL_START_TIME))
  MINUTES=$((DURATION / 60))
  SECONDS_REM=$((DURATION % 60))
  TIME_RESULT=$(printf "%02d:%02d" $MINUTES $SECONDS_REM)

  echo -e "${GREEN}Done...${NC}"
  gum format "# Success" "CuriOS was successfully installed in ${TIME_RESULT}!" "Remember to remove USB installer!"
  if gum confirm "Reboot now?"; then
    reboot now
  fi
fi
